ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<int:i>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cart_view,name="cartview"),
    path('cartremove/<int:i>',views.cart_remove,name="cartremove"),
    path('delete/<int:i>',views.delete,name="delete"),
    path('orderform',views.orderform,name="orderform"),
    path('status/<u>',views.payment_status,name="status"),
    path('orders/', views.orders, name="orders"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search',include('search.urls')),
    path('cart/',include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
       path('',views.search_product,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name="categories"),
    path('products/<int:p>',views.allproducts,name="products"),
    path('details/<int:i>',views.alldetails,name="details"),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('add_categories/',views.add_categories,name="add_categories"),
    path('add_products/',views.add_products,name="add_products"),
    path('addstock/<int:p>',views.addstock,name="addstock"),

]

ecommerce/cart/models.py
from django.db import models

from shop.models import Product
from django.contrib.auth.models import User


class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price*self.quantity

class Order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone_no=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=20,blank=True)
    ordered_date=models.DateTimeField(auto_now_add=True)


    payment_status=models.CharField(max_length=20,default="pending")

    delivery_status=models.CharField(max_length=20,default="pending")


class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Payment,Order_details
from shop.models import Product
import razorpay
from django.contrib.auth.models import User
from django.contrib.auth import login
@login_required
def add_to_cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if(p.stock>0):

            c.quantity += 1
            c.save()
            p.stock-=1
            p.save()

    except:
        if(p.stock>0):
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock-=1
            p.save()

    return redirect('cart:cartview')


@login_required
def cart_view(request):
    u=request.user
    total=0
    c=Cart.objects.filter(user=u)
    for i in c:
        total+=i.quantity*i.product.price



    context={'cart':c,'total':total}

    return render(request,'cart.html',context)

@login_required
def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if(c.quantity>1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()
        else:
            c.delete()
            p.stock += 1
            p.save()

    except:
        pass
    return redirect('cart:cartview')

@login_required
def delete(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        c = Cart.objects.get(user=u, product=p)
        c.delete()
        p.stock += c.quantity
        p.save()
    except:
        pass
    return redirect('cart:cartview')

@login_required
def orderform(request):
    if(request.method=="POST"):
        address=request.POST['a']
        phone=request.POST['p']
        pin=request.POST['pi']

        u=request.user

        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price

        total=int(total*100)
        client=razorpay.Client(auth=('rzp_test_vHsxWg7DZdBnwm','K75FS6Ls1dGXk1ySVSn3h4e9'))

        response_payment=client.order.create(dict(amount=total,currency="INR"))#CREATE AN ORDER

        order_id=response_payment['id']
        order_status=response_payment['status']
        if(order_status=="created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:  #for each ite
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone_no=phone,pin=pin,order_id=order_id)
                o.save()
            else:
                pass
            response_payment['name']=u.username #additional information name

            context={'payment':response_payment}


            return render(request, 'payment.html',context)

    return render(request,'orderform.html')


from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def payment_status(request,u):
    user = User.objects.get(username=u)
    if(not request.user.is_authenticated): #if user is not authenticated
        login(request,user)#allowing request user to login

    if(request.method=="POST"):
        response=request.POST
        print(response)
        print(u)

        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }
        client=razorpay.Client(auth=('rzp_test_vHsxWg7DZdBnwm','K75FS6Ls1dGXk1ySVSn3h4e9'))
        print(client)
        try:
            status=client.utility.verify_payment_signature(param_dict)
            print(status)
            p = Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id = response['razorpay_payment_id']
            p.paid = True  # change the paid status to tre
            p.save()


            user=User.objects.get(username=u)

            o=Order_details.objects.filter(user=user,order_id=response['razorpay_order_id'])
            print(o)
            for i in o:
                i.payment_status="paid"
                i.save()

            c=Cart.objects.filter(user=user)
            c.delete()



        except:
            pass


    return render(request,'payment_status.html',{"status":status})



def orders(request):
    u=request.user
    o=Order_details.objects.filter(user=u,payment_status="paid")
    context={'orders':o}


    return render(request,'your_orders.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def search_product(request):
    query=""
    p=None
    if(request.method=="POST"):
        query=request.POST['q']

        if(query):
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request,'search.html',{'product':p,'q':query})

ecommerce/templates/add_categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container mt-5 p-4 bg-light rounded shadow-lg" style="max-width: 600px;">
        <h2 class="text-center mb-4">Add Categories</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

          <div class="mb-3">
  <label class="form-label">Category Name</label>
  <input type="text" class="form-control" name="n" placeholder="Enter the Category Name">
</div>
            <div class="mb-3">
  <label class="form-label">Image</label>
  <input type="file" class="form-control" name="i">
</div>
          <div class="mb-3">
  <label class="form-label">Description</label>
  <textarea class="form-control" name="d" rows="3"></textarea>
</div>

          <div class="mb-3 text-center">
  <input type="submit" value="Submit">
</div>

        </form>
    </div>

{% endblock %}

ecommerce/templates/add_products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container mt-5 p-4 bg-light rounded shadow-lg" style="max-width: 600px;">
        <h2 class="text-center mb-4">Add Products</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

          <div class="mb-3">
  <label class="form-label">Product Name</label>
  <input type="text" class="form-control" name="pn" placeholder="Enter the Product Name">
</div>
            <div class="mb-3">
  <label class="form-label">Image</label>
  <input type="file" class="form-control" name="i">
</div>
          <div class="mb-3">
  <label class="form-label">Description</label>
  <textarea class="form-control" name="d" rows="3"></textarea>
</div>
            <div class="mb-3">
  <label class="form-label">Stock</label>
  <input type="number" class="form-control" name="s" placeholder="Enter the Stock">
</div>
            <div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="Enter the Price">
</div>
            <div class="mb-3">
  <label class="form-label">Category Name</label>
            <select name="cn" class="form-select" aria-label="Default select example">
  <option selected>Select category</option>
                {% for i in links %}
                <option value="{{i.name}}">{{i.name}}</option>
                {% endfor %}
</select>
            </div>

          <div class="mb-3 text-center">
  <input type="submit" value="Submit">
</div>

        </form>
    </div>

{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<center>
    <div class="container mt-5 p-3 w-25" style="margin-bottom:100px;">
        <h2 class="text-center">Add Stock</h2>
        <form method="post">
            {% csrf_token %}
             <div class="mb-3">
  <label class="form-label">Stock</label>
  <input type="number" class="form-control" value="{{product.stock}}" name="n" placeholder="Enter the Stock">
</div>
     <div class="mb-3 text-center">
  <input type="submit" value="Submit">
</div>
        </form>
    </div>
</center>

     {% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
<!--<div class="container-fluid text-center">-->
<!--    <img src="{% static 'images/shopping-cart_1121779.png' %}" height="70px" width="70px">-->
<!--</div>-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mt-4 shadow-lg">
  <div class="container-fluid">
      <img src="{% static 'images/shopping-cart.png' %}" height="40px" width="40px">
    <a class="navbar-brand fs-3 fw-bold" href="#"></i>ShopiFy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-6 fw-ligh mx-auto">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:categories' %}">Home</a>
        </li>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Allcategories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
          {% if user.is_superuser == False %} <!--normal user -->
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}">Cart<sup>{{c}}</sup></a>
        </li>
           <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'cart:orders' %}">Your Orders</a>
        </li>



          {% else %}
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:add_categories' %}">Add Categories</a>
        </li>
          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:add_products' %}">Add Products</a>
        </li>
          {% endif %}

          <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>

{% block content %}
{% endblock %}
<footer class="footer">
  <p class="text-center"><i class="fa-regular fa-copyright me-1" aria-hidden="true"></i>myshop@pvt.ltd</p>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

    {% endblock %}
{% block content %}
<center>
   <div class="container mt-5 p-3" style="margin-bottom:100px;">
       <div class="row">
           <h2>shopping cart</h2>
           <div class="col-7">
               <table class="table table-bordered border-1  shadow-lg text-light">
                   <tr>
                       <th colspan="6" class="text-center fs-5">Cart items</th>
                   </tr>
                   {% for i in cart %}
                   <tr>
                       <td><img src="{{i.product.image.url}}" height="100px" width="100px" ></td>
                       <td>{{i.product.name}}</td>
                       <td>unit price:{{i.product.price}}<br>
                       Quantity:{{i.quantity}}
                       <td>subtotal:{{i.subtotal}}</td>
                       <td class="pt-3">
                           {% if i.product.stock > 0 %}
                           <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus fs-5 text-light mx-1"></i></a>
                           <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-circle-minus fs-5 text-light mx-1"></i></a>
                           <a href="{% url 'cart:delete' i.product.id %}"><i class="fa-solid fa-trash fs-5 text-light mx-1"></i></a>
                       {% else %}
                           <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-circle-minus fs-5 text-light mx-1"></i></a>
                           <a href="{% url 'cart:delete' i.product.id %}"><i class="fa-solid fa-trash fs-5 text-light mx-1"></i></a>
                       {% endif %}

                       </td>


                   </tr>
                   {% endfor %}
               </table>
           </div>
                    <div class="col-4">
               <table class="table table-bordered border-1 shadow-lg text-light">
                   <tr>
                       <th colspan="4" class="text-center fs-5">Check Out</th>

                   </tr>
                   <tr><td class="">Total price:{{total}}</td></tr>
               </table>
                        <div class="d-flex justify-content-between ">
                        <a href="{% url 'cart:orderform' %}"class="btn btn-dark text-light">Order Now</a>
                        <a href="{% url 'shop:categories' %}" class="btn btn-dark text-light">Continue Shopping</a>
                    </div>
           </div>
       </div>
{% endblock %}
   </div></center>

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <img src="{% static 'images/portrait.jpg' %}" height="600px" width="100%">
</div>
<div class="row mt-3 px-3" style="margin-bottom:100px">
    <div class="cool-12">
        <h3 class="text-center fw-bold text-light mt-5 mb-5">Our Collections</h3>
        <p style="text-align:justify;line-height:2" class="fs-5">Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph. A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph.</p>
    </div>
</div>

<div class="container mt-5 mb-5">

    <div class="row">
        {% for i in cat %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.name}}</h5>

      <a href="{% url 'shop:products' i.id %}" class="btn btn-secondary">Products</a>
  </div>
</div></div>
        {% endfor %}
    </div>
</div>


{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
<div class="card mb-3 mx-auto" style="max-width:70%;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{product.image.url}}" class="rounded-start" height="400px" width="100%" alt="...">
    </div>
    <div class="col-md-8 mt-4 p-3">
      <div class="card-body">
        <h2 class="card-title">{{product.name}}</h2>
        <h5 class="card-text">{{product.price}}</h5>
        <h5 class="card-text">{{product.stock}}</h5>
        <h4>Product Details</h4>
        <p class="card-text" style="line-height:1.5;text-align:justify">{{product.desc}}</p>
        {% if user.is_superuser == True %}
         {% if product.stock > 0 %}
        <h5>Product In Stock</h5>
        <a href="{% url 'shop:addstock' product.id %}" class="btn btn-secondary">ADD STOCK</a>
        {% else %}
        <h5>Product Out Stock</h5>
        <a href="{% url 'shop:addstock' product.id %}" class="btn btn-secondary">ADD STOCK</a>
        {% endif %}

        {% else %}
        {% if product.stock > 0 %}
        <a href="{% url 'cart:addtocart' product.id %}" class="btn btn-secondary">ADD TO CART</a>
        {% else %}
        <h5>Out of Stock</h5>
        {% endif %}
        {% endif %}

      </div>
    </div>
  </div>
</div>
  </div>

{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container mt-5 p-3 w-50" style="margin-bottom:100px;">

<h2 class="text-center">login</h2>
<form method="POST">
  {% csrf_token %}
    <div class="container w-50">
<div class="mb-2 p-2">
  <label class="form-label mt-3">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter the username">
</div>
<div class="mb-2 p-2">
  <label class="form-label mt-3">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter the password">
</div>
    <div class="mb-2 p-2">

  <input type="submit" value="submit" class="form-control">
</div>
</form>
   {% if messages %}
<ul class="messages">
  {% for message in messages %}
   <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>

  {% endblock %}
</body>
</html>

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<center>
    <div class=""></div>
    <h2>billing details</h2>
<form method="POST">
  {% csrf_token %}
<div class="mb-2 p-2" >
  <label class="form-label mt-3">Address</label>
  <input type="text" class="form-control" name="a" placeholder="" >
</div>
    <div class="mb-2 p-2" >
  <label class="form-label mt-3">Phone Number</label>
  <input type="number" class="form-control" name="p" placeholder="" >
</div>
    <div class="mb-2 p-2" >
  <label class="form-label mt-3">Pin Code</label>
  <input type="number" class="form-control" name="pi" placeholder="" >
</div>
    <div class="mb-2 p-2" >

  <input type="submit" class="form-control btn btn-dark">

</div>


{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 p-5 bg-light w-50 shadow-lg rounded">

<form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" class="text-center m-5 p-5"  method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_vHsxWg7DZdBnwm" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="ShopiFy"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#0ee8a7"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>






{% endblock %}

ecommerce/templates/payment_status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 p-5 bg-light w-50 shadow-lg rounded">
      {% if status == True %}
    <h2 class="text-center">payment succesfull</h2>
    {% else %}
    <h2 class="text-center">Payment Failed.Please Try Again...</h2>
    {% endif %}

</div>






{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-12">
    <img src="{{cat.image.url}}" height="600px" width="100%">
</div>
<div class="row mt-3 px-3" style="margin-bottom:100px">
    <div class="cool-12">
        <h3 class="text-center fw-bold text-light mt-5 mb-5">{{cat.name}}</h3>
        <p style="text-align:justify;line-height:2" class="fs-5">{{cat.desc}}</p>
    </div>
</div>
<div class="container mt-5 mb-5">

    <div class="row">
        {% for i in product %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.name}}</h5>
      <h5 class="card-title">{{i.price}}</h5>

      <a href="{% url 'shop:details' i.id %}" class="btn btn-secondary">Details</a>
  </div>
</div></div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<h2 class="text-center">Register</h2>
<form method="POST">
  {% csrf_token %}
<div class="mb-2 p-2" >
  <label class="form-label mt-3">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter the username" >
</div>
<div class="mb-2 p-2">
  <label class="form-label mt-3">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter the password" >
</div>
  <div class="mb-2 p-2">
  <label class="form-label mt-3">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter the confirm password" >
</div>
<div class="mb-2 p-2">
  <label class="form-label mt-3">First Name</label>
  <input type="text" class="form-control" name="f" placeholder="enter the first name" >
</div>
<div class="mb-2 p-2">
  <label class="form-label mt-3">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="enter the last name" >
</div>
<div class="mb-2 p-2">
  <label class="form-label mt-3">Email</label>
  <input type="email" class="form-control" name="e" placeholder="enter the email" >
</div>
    <div class="mb-2 p-2">
  <input type="submit" Value="Submit">
</div>
</form>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-12">
<!--    <img src="" height="600px" width="100%">-->
</div>
<!--<div class="row mt-3 px-3" style="margin-bottom:100px">-->
<!--    <div class="cool-12">-->
<!--        <h3 class="text-center fw-bold text-light mt-5 mb-5">{{cat.name}}</h3>-->
<!--        <p style="text-align:justify;line-height:2" class="fs-5">{{cat.desc}}</p>-->
<!--    </div>-->
<!--</div>-->
<div class="container mt-5 mb-5">

    {% if product == None %}
    <h3>no result</h3>
    {% else %}
    <div class="row">
        {% for i in product %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.name}}</h5>
      <h5 class="card-title">{{i.price}}</h5>

      <a href="{% url 'shop:details' i.id %}" class="btn btn-secondary">Details</a>
  </div>
</div></div>
        {% empty %}
        <h3>no result</h3>
        {% endfor %}

    </div>{% endif %}

</div>

{% endblock %}